fabric-ds/react

docs/src/Main.tsx
docs/src/components/Nav.tsx
package.json
packages/slider/README.md
packages/slider/docs/Slider.mdx
packages/slider/package.json
packages/slider/src/RangeSlider.tsx
packages/slider/src/RegularSlider.tsx
packages/slider/src/index.ts
packages/slider/src/useInnerWidth.tsx
packages/slider/src/utils.ts
packages/slider/stories/Slider.stories.tsx
packages/slider/tsconfig.json
packages/utils/src/index.ts
packages/utils/src/useElementSizeObserver.ts
yarn.lock

This PR does the initial work to get the slider component ported from troika react.
Specifically
* Docs page
* Stories
* Basic component implementation
Still remaining

feat: add slider component

---

docs/src/Main.tsx
docs/src/components/Nav.tsx
package.json
packages/box/docs/Box.mdx
packages/box/package.json
packages/box/src/component.tsx
packages/box/src/index.ts
packages/box/src/props.tsx
packages/box/stories/Box.stories.tsx
packages/box/tsconfig.json
packages/breadcrumbs/docs/Breadcrumbs.mdx
packages/slider/docs/Slider.mdx
packages/utils/package.json
yarn.lock

* Updates Vite
* Fixes missing dep in utils
* Adds box component

Add box component

---

docs/src/Main.tsx
docs/src/components/Nav.tsx
packages/card/README.md
packages/card/docs/Card.mdx
packages/card/package.json
packages/card/src/component.tsx
packages/card/src/index.ts
packages/card/src/props.tsx
packages/card/stories/Card.stories.tsx
packages/card/tsconfig.json
packages/toggle/docs/Toggle.mdx
packages/toggle/package.json
packages/toggle/src/component.tsx
packages/toggle/src/item.tsx
packages/toggle/src/props.tsx
packages/toggle/stories/Checkbox.stories.tsx
packages/toggle/stories/Radio.stories.tsx
packages/toggle/stories/RadioButtons.stories.tsx

This PR introduces the Card component to React.
I also had to make a few changes (adding controlled / uncontrolled states) to the existing [Toggle](https://opensource.finn.no/fabric-react/#/toggle) component to support having toggles in cards, as per the Vue example.
[Read docs](https://opensource.finn.no/fabric-react/#/card)

Added Card Component

---

packages/switch/src/component.tsx
packages/switch/src/props.tsx
packages/switch/stories/Switch.stories.tsx

The code should now be more semantically correct.

Improved Switch component

---

packages/button/src/component.tsx
packages/button/stories/Button.stories.tsx

This makes it possible for screen readers to detect the "loading" state.

fix(button): Add progressbar element

---

packages/modal/README.md
packages/modal/package.json
packages/slider/src/RangeSlider.tsx
packages/slider/src/RegularSlider.tsx
packages/slider/src/props.ts
packages/slider/src/utils.ts
packages/slider/stories/Slider.stories.tsx

- Ensure that ranged sliders have aria-labels on both handles.
- Fix aria-valuenow not always displaying correct value.
- Make larger step increments when using PageUp or PageDown to adjust the slider.

fix(slider): Various a11y issues

---

packages/box/docs/Box.mdx
packages/box/src/clickable.tsx
packages/box/src/component.tsx
packages/box/src/index.ts
packages/box/src/props.tsx
packages/box/stories/Box.stories.tsx
packages/expandable/docs/Expandable.mdx
packages/expandable/package.json
packages/expandable/src/component.tsx
packages/expandable/src/props.tsx
packages/expandable/stories/Expandable.stories.tsx

Added a new animated variant to the expandable component and refactor to Box component.

Animated expandable

---

packages/card/docs/Card.mdx
packages/card/stories/Card.stories.tsx

Set up an example if a user wishes to create a Card that redirects the user somewhere using an anchor element while remaining accessible. This uses the Clickable implementation that we see in Box examples too.

Card examples using anchor redirects

---

docs/src/Main.tsx
index.html
package.json
packages/index.ts
packages/pill/docs/Pill.mdx
packages/pill/src/component.tsx
packages/pill/src/index.ts
packages/pill/src/props.tsx
packages/pill/stories/Button.stories.tsx

Adds the Pill component to React.

Implemented Pill Component

---

packages/index.ts

Include helpers in build (DeadToggle and Clickable).

Export helpers

---

package.json
packages/modal/src/component.tsx

Added enter and leave animation using `@headless/ui`'s Transition component. (https://github.com/fabric-ds/issues/issues/6)

Modal animation

---

packages/switch/src/component.tsx
packages/switch/src/props.tsx

Support event parameter for Switch. I.e when you are using it with forms.

Support event for switch component

---

packages/combobox/docs/Combobox.mdx
packages/combobox/src/component.tsx
packages/combobox/src/props.ts
packages/combobox/src/utils.ts
packages/combobox/stories/Combobox.stories.tsx
packages/utils/src/useId.ts

Been working through this list https://github.com/fabric-ds/issues/issues/37 after some great feedback from our [weekly q&a a few weeks ago](https://github.com/fabric-ds/issues/blob/master/weekly-q-and-a-sessions/06-01-2022.md#vegard-feedbackdiscussion-on-combobox).

Combobox improvements from feedback

---

package.json

Fixes https://github.com/fabric-ds/issues/issues/64

build: add cjs bundle for SSR

---

.github/renovate.json
.github/workflows/deploy.yml
.github/workflows/release.yml
package.json
release.config.cjs
release.config.js
renovate.json

https://github.com/fabric-ds/issues/blob/master/rfcs/0004-releases.md

Automate publishing with semantic release

---

docs/src/Main.tsx
index.html
packages/alert/docs/Alert.mdx
packages/alert/src/component.tsx
packages/alert/src/index.ts
packages/alert/src/props.tsx
packages/alert/stories/Alert.stories.tsx
packages/index.ts

Fixes [FRON-593](https://finn-jira.atlassian.net/browse/FRON-593)
Add inline alert component to feedback indicators based on Figma sketches:
https://www.figma.com/file/gpHv46zswMNeepUDyQfpS8/Feedback-indicators?node-id=274%3A31588

feat(packages): add inline Alert component

---

packages/_helpers/index.ts
packages/_helpers/props.ts
packages/_helpers/unstyled-heading.tsx
packages/expandable/docs/Expandable.mdx
packages/expandable/src/component.tsx
packages/expandable/src/props.tsx
packages/expandable/stories/Expandable.stories.tsx

TODO: Make styling that preserves original visual appearance (if necessary).

Add headingLevel prop to Expandable

---

.github/workflows/deploy.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
package.json
packages/_helpers/expand-transition.tsx
packages/_helpers/index.ts
packages/_helpers/props.ts
packages/_helpers/unstyled-heading.tsx
packages/alert/docs/Alert.mdx
packages/alert/src/component.tsx
packages/alert/src/props.tsx
packages/attention/src/component.tsx
packages/card/src/component.tsx
packages/expandable/docs/Expandable.mdx
packages/expandable/src/component.tsx
packages/expandable/src/props.tsx
packages/expandable/stories/Expandable.stories.tsx
packages/toggle/docs/Toggle.mdx
packages/toggle/src/component.tsx
packages/toggle/src/item.tsx
packages/toggle/src/props.ts
packages/toggle/stories/Checkbox.stories.tsx

Release v1.4.0

---

CHANGELOG.md
package.json
packages/alert/src/props.tsx
packages/expandable/src/component.tsx

3 small bug fixes to be released onto the main channel.

Fabric React Release 21/09/2022

---

packages/_helpers/expand-transition.tsx
packages/expandable/stories/Expandable.stories.tsx

Reverts fabric-ds/react#151 that didn't get published with semantic release due to a typo in the commit message

Revert "Fix(expandable): glitching animated expansion"

---

packages/toggle/docs/Toggle.mdx
packages/toggle/src/component.tsx
packages/toggle/src/item.tsx
packages/toggle/src/props.ts
packages/toggle/stories/Checkbox.stories.tsx

Fixes https://github.com/fabric-ds/issues/issues/110 / [FRON-680](https://finn-jira.atlassian.net/browse/FRON-680?atlOrigin=eyJpIjoiNDcwM2E3MTdhMGQ4NGU5ZTgxMWRkZGU0Y2RhNDA4NmEiLCJwIjoiaiJ9)
Additionally: fix a React input error where we were trying to control an uncontrolled input value.

feat(toggle): handle indeterminate state in a select-all checkbox

---

CHANGELOG.md
package-lock.json
package.json
packages/modal/src/component.tsx

Time to cut a release!
Non breaking fixes which should get auto documented in the changelog by semantic release.

Release: Wednesday 1st March 2023
