fabric-ds/react

packages/box/src/component.tsx
packages/box/stories/Box.stories.tsx

Move the button role from the Box element to a separate child element to prevent a11y issues when children of the Box are block elements, interactive elements, or some other type of descendants that would be invalid inside a button.
This feels kind of hacky, and I'm open to other suggestions and solutions.

fix: Button role with Box

---

packages/checkbox/package.json
packages/checkbox/src/Checkbox.tsx
packages/checkbox/src/CheckboxGroup.tsx
packages/radio/src/Radio.tsx
packages/radio/src/RadioGroup.tsx
packages/select/package.json
packages/slider/package.json
packages/slider/src/RangeSlider.tsx
packages/slider/src/RegularSlider.tsx
packages/tabs/package.json
packages/textarea/package.json
packages/textarea/src/TextArea.tsx
packages/textfield/package.json
packages/textfield/src/TextField.tsx

Many of these warnings are accessibility warnings which, after some discussion with @tor-martin-storsletten, I concluded that we could perhaps do without as the thinking is that we can't really expect to catch all developer accessibility errors by throwing console warnings at them. Please jump in here with thoughts @tor-martin-storsletten 
The second category of warnings is deprecation warnings which I think we can do without as we are breaking very hard between Troika and Fabric.
cc/ @Skadefryd @pearofducks

fix: remove tiny warning (accessibility warnings and deprecation warnings) from components

---

docs/src/components/Nav.tsx

This adds a section in the left hand nav that links to the other Fabric sites

docs: add cross site navigation

---

packages/modal/src/component.tsx

Modal previously wouldn't dismiss when you clicked on the backdrop.

Dismiss modal on click

---

packages/steps/src/step.tsx

I also moved aria-current to the SVG with the checkmark because it can be a little bit too much to hear "Current step" for every piece of content within the currently active step. Now it will only say it once, when the user reads the checkmark (the SVG element).

fix(steps): Expose states to screen readers

---

packages/toggle/src/component.tsx
packages/toggle/src/item.tsx
packages/toggle/stories/Checkbox.stories.tsx
packages/toggle/stories/RadioButtons.stories.tsx

- No legend element outside fieldset element.
- Same semantics for type "radio" and "radio-button".
- Always set aria-describedby if helper text is available.
- Don't set aria-errormessage on input element if it's not invalid.
- Add single option help text story.

fix(toggle): A11y issues

---

packages/button/src/component.tsx
packages/button/stories/Button.stories.tsx

Previously, the button class wouldn't be set on the container if there was an href prop present. Switched this out to check for the link prop instead. Should solve issue.

Append button class properly

---

eik.json
package.json
packages/pill/docs/Pill.mdx
packages/pill/src/component.tsx
packages/pill/src/props.tsx

Allow the user to set custom labels for the open/click and close button in the Pill component.

Custom SR labels to Pill

---

README.md
package.json

This should ™️ make it so you can just run `npm version major|minor|patch` to do all versioning and publishing in a single hit.

chore: simplify publishing

---

packages/combobox/src/component.tsx

Swaps the order of `onChange` and `onSelect` in the `handleSelect` in order to improve the control over the event listener

fix(combobox): swap onChange and onSelect order

---

packages/button/src/component.tsx
packages/button/stories/Button.stories.tsx
packages/card/src/component.tsx
packages/combobox/src/component.tsx
packages/tabs/src/component-tab-panel.tsx
packages/tabs/src/component-tab.tsx

React will complain when we spread props that are non-native, such as custom boolean attributes that are only meant for the component to handle different visual styles, elements rendered, etc. This PR ensures that we only spread native or semantically correct props.

Fix React dev errors

---

packages/combobox/docs/Combobox.mdx
packages/combobox/src/component.tsx
packages/combobox/stories/Combobox.stories.tsx

This PR improves the control over the combobox component by: 
- removing the `props.onChange` call from the `handleSelect` fn, giving the users the option to set a value manually in the `onSelect` prop fn
- clearing the `options` state if `props.options` gets cleared
I also made it so that the menu won't open unless the input field has a value _and_ there are options available. This will prevent an empty menu showing up (e.g ⬇️ )
**EDIT:**
It's worth noting that the removal of `props.onChange` might "break" the expected functionality for some users, so it might be a good idea to write a quick post in slack before publishing 😛

feat(combobox): improve control over input field and options

---

eik.json

Pretty straight forward change to use the import map for React v17. Removes the old Troika map as well.
What this actually means:
* When people use this version of the library in production, components will be referring to our version of React v17 on the Eik server. 
**Example:**
In their own code:
```js
import { Button } from '@fabric-ds/react';
```
Then they run a build using esbuild or rollup with the Eik plugin and that code will be transformed to:
```js
import { Button } from 'https://assets.finn.no/pkg/@fabric-ds/react/v1/index.js';
```
and then `https://assets.finn.no/pkg/@fabric-ds/react/v1/index.js` in turn has already had all its internal references to React mapped to `https://assets.finn.no/npm/react/v17/react.production.min.js`
Once we merge this PR we will need to:
* Update …

chore!: use React v17 for Eik build

---

packages/combobox/src/component.tsx

Noticed a bug introduced in #62 where the `Ingen treff, viser ...` sr-only span was missing, as the menu/container wouldn't render at all if no options were present. 
This PR fixes that issue by reverting the code that prevented the menu from rendering, and hiding the menu visually instead (if there are no options)

fix(combobox): hide empty menu using css instead of not rendering it

---

package.json

There was a problem with the esbuild plugin that meant that import maps were not being read (and therefore react was being inlined). This fixes that by updating to the latest version of the esbuild plugin.
You can read more about the change to the esbuild plugin here: https://github.com/eik-lib/esbuild-plugin/pull/36

fix: upgrade esbuild plugin to support eik config defined in package.json

---

packages/combobox/src/component.tsx

This PR adds an `id` attribute to the combobox option elements. The option ID is referenced by the `aria-activedescendant` attribute on the combobox input, as described here https://www.w3.org/TR/wai-aria-practices-1.2/#listbox-popup-keyboard-interaction
The unit tests in this repo do not seem to be in a runnable state, so I didn't add any tests for this change.
Before, with missing `id`:
After:

fix: add missing id to combobox option

---

packages/combobox/src/component.tsx
packages/combobox/stories/Combobox.stories.tsx

This PR allows the `Enter` key event to bubble up to an enclosing form. This is useful for use cases where the combobox input is used for free-text search.

fix: Enter key event

---

packages/expandable/src/component.tsx

For screen reader users the body of the expandable is available at all times, making the "open"/"close" button confusing when no new content shows up when the button switches to aria-expanded="true". 
Aria-hidden will now hide the content for screen readers and make the experience similar to visual users.

Hides expandable body for screen readers when closed

---

packages/combobox/src/component.tsx
packages/combobox/src/props.ts
packages/combobox/stories/Combobox.stories.tsx
packages/textfield/src/component.tsx
packages/textfield/src/props.ts

When trying to set the `autoComplete="off"` prop on `Combobox`(which is inherited from `TextField`), I get an error from the TS compiler saying:
```
(property) autoComplete?: undefined
Type 'string' is not assignable to type 'undefined'.ts(2322)
index.d.ts(615, 9): The expected type comes from property 'autoComplete' which is declared here on type 'IntrinsicAttributes & { autoComplete?: boolean | undefined; autoFocus?: boolean | undefined; className?: string | undefined; defaultValue?: string | undefined; ... 21 more ...; value?: string | undefined; } & Pick<...> & RefAttributes<...>'
```
I don't know why the type is reported as `undefined`, but the correct type should AFAIK be string, and not boolean https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete
This …

fix: use inital type for input autocomplete prop

---

packages/_helpers/affix.tsx
packages/combobox/docs/Combobox.mdx

This PR adds support for labeling the `Affix` component with an `aria-label` attribute. This would make the search and clear buttons accessible to screen readers, since the buttons only contain an icon, and no descriptive text.
It would also be possible to add more props, like `aria-labelledby` and `aria-describedby`, according to the recommended guidelines https://www.w3.org/TR/wai-aria-practices-1.2/#button
Please feel free to suggest improvements to this PR while reviewing 😄

fix: support aria-label prop on affix component

---

packages/textfield/src/component.tsx

This PR simplifies the DOM for the `TextField` component by removing the outermost `div`, which is redundant. All the examples in the storybook seem to be fine.

fix: remove redundant div around textfield input

---

packages/_helpers/affix.tsx

This PR adds button type attributes to `Affix` buttons, specifically `type="submit"` for search, and `type="reset"` for clear. This prevents the clear button from submitting the enclosing form of the textfield.
I believe this code could be improved by extracting a separate `ButtonAffix` component as suggested in #76 .

fix: add button type attribute to affix buttons

---

package.json

17.0.3 does not exist. Should be 17.0.2 which is the current latest.

fix: fix incorrect peer dep on React

---

package.json
packages/modal/src/component.tsx

This reverts commit 08476448c2d4401c35a4217204f11019c3d4ef68.
Reasons:
1. The commit triples the bundle size
2. The addition of the headless ui package breaks SSR
Next Steps:
After merging this PR, implementations between Vue and React will once again be different. This seems acceptable for now but I have created a ticket to look further at lining up animations across implementations here: https://github.com/fabric-ds/issues/issues/67

Revert "Add modal animation"

---

packages/box/src/component.tsx
packages/expandable/src/component.tsx

React would complain in dev mode about custom props being spread onto the underlying dom element. This caused frustration and unnecessary development time spent trying to solve something that lies within Fabric and not directly in the control of the consumers of the library.
This PR fixes https://github.com/fabric-ds/react/issues/82

Fix custom prop error message

---

packages/modal/docs/Modal.mdx

Changes from disable to displaying a message when clicking the button (in the case where the user hasn't clicked the checkbox)
Fixes https://github.com/fabric-ds/issues/issues/93

docs: don't disable button on modal

---

packages/_helpers/affix.tsx

Screen readers will use the aria-label on the SVG only if the button wrapper has no label. So in that sense, these default labels are like fallbacks.

Add aria-label to Affix icons

---

packages/_helpers/expand-transition.tsx
packages/_helpers/index.ts
packages/alert/src/component.tsx
packages/expandable/src/component.tsx

Adds a check if `expandableRef.current` exists, which fixes a TS error `Argument of type 'null' is not assignable to parameter of type 'HTMLElement'.`
Renames component from `AnimatedExpansion` to `ExpandTransition` to align the naming with other packages (Vue and Elements)

Fix a bug in AnimatedExpansion

---

package.json
packages/attention/src/component.tsx

This PR replaces the classes that have been abstracted to component-classes in @fabric-ds/css.

refactor: replace attention classes

---

esbuild.mjs
package.json

There was no support for React v16 in 1.2.0 so no need to add it now so I have removed building a v16 bundle.
Additionally, I realised that by changing the name of index.js, I was actually causing a breaking change. To avoid that, I've created 2 bundles of v17. One is called index.js for backwards compatible reasons and one is called fabric-react-17.js for future proofing.

fix: remove unused React v16 and add backwards compatible v17 bundle

---

CHANGELOG.md
esbuild.mjs
package.json

We need to cut a release to remove a breaking change in the Eik bundles by adding a backwards compatible build.

Fix Eik bundles to keep backwards compatibility with 1.2.0

---

packages/expandable/docs/Expandable.mdx
packages/expandable/src/component.tsx
packages/expandable/stories/Expandable.stories.tsx

Fixes [FRON-437](https://finn-jira.atlassian.net/jira/software/projects/FRON/boards/437?selectedIssue=FRON-635)
With this change it is possible to control Expandable's title style and add to it any additional React elements, like icons, without messing up chevron's alignment. `title` will be assigned a `h4` style as long as its type is `string`.

feat(expandable): make Expandable accept custom title

---

packages/expandable/src/component.tsx

This change brings back rotation animation of `Expandable`'s chevron.

fix(expandable): use local expanded state to control chevron's rotation

---

packages/alert/src/component.tsx

Fixes this issue - https://sch-chat.slack.com/archives/C01GYKPJVFT/p1656079441413319?thread_ts=1655729953.396319&cid=C01GYKPJVFT

fix: alert icon gets flexed when content has overflow

---

packages/_helpers/expand-transition.tsx
packages/alert/docs/Alert.mdx
packages/alert/src/component.tsx
packages/alert/src/props.tsx
packages/expandable/src/component.tsx

Make React `Alert` consistent with Elements `f-alert` in terms of accessibility:
- set default "alert" role in `Alert` component
- handle elements with "alert" role nested in `Alert` component, so that screen readers recognize them
- improve the accessibility of Alert component docs
- As it was applied in Fabric Elements, `ExpandTransition` component now renders `children` only if `show` property value is `true`

feat(alert): improve accessibility of the Alert component and docs

---

package.json
packages/attention/src/component.tsx

Fixes an issue with `Attention`'s position on first render reported in https://sch-chat.slack.com/archives/C01GYKPJVFT/p1660561211389669
Adds aria labels to `Arrow` component

Bugfix - attention position

---

packages/expandable/src/component.tsx

Fixes an issue where contents didn’t expand if `expanded` prop was updated outside of `Expandable`, e.g. by another button.
Before:
After:

Listen for "expanded" prop change if it's updated outside of Expandable

---

packages/expandable/src/component.tsx

Unexpected behaviour of the `Expandable` component.
When Expandable is inside the `<form/>` element it triggers its submit on click.
Reproduced here: [Sandbox](https://codesandbox.io/s/fabric-expandable-submit-mm4gbs?file=/src/App.jsx)
As can be seen on the sandbox the submit handler fires on Expandable click.
The bug probably is due to the missing type="button" attribute within <button/> used inside the Expandable component. Default value of type is submit therefore causing the form submit.

fix(expandable): set button type to 'button' to prevent default submit behaviour

---

packages/alert/src/props.tsx

`role` prop of `Alert` component has a default value so it shouldn't be required.

fix(alert): type 'role' prop as optional

---

packages/toggle/src/item.tsx

The additional invisible label span was causing space to be reserved and upon discussion it seems like the only need for an invisible label is for screen readers and that's already covered by the sr-only span. It seems like we can just remove the invisible w-0 span.
@martin-storsletten are you able to sense check this change?

fix: remove additional hidden label

---

packages/_helpers/expand-transition.tsx
packages/expandable/stories/Expandable.stories.tsx

https://github.com/fabric-ds/react/commit/fd69c9a80c2a453f86841044f95eb673e599a497 removed base styles which is needed when using element-collapse. Basically not have a `overflow: hidden` and `height: 0px`, makes it have default values causing the glitching effect.
However when in default expanded mode, these styles must not be there.
Closes
https://github.com/fabric-ds/issues/issues/108
https://github.com/fabric-ds/react/issues/144
If there is a simpler solution, please apply it! 😁 At least this does seem to work.

Fix(expandable): glitching animated expansion

---

package.json

Not only was this not being used but we were including it in both deps and devdeps at the same time with 2 different major versions 🤦

fix: remove unused react-spring dependency

---

packages/breadcrumbs/src/component.tsx
packages/breadcrumbs/stories/Breadcrumbs.stories.tsx

Fixes https://github.com/fabric-ds/issues/issues/115
Flatten children array before calling interleave to ensure correct display of breadcrumbs.
Before:
After:

fix(breadcrumbs): handle array of nodes passed as children

---

.storybook/preview-head.html
index.html
packages/attention/docs/Attention.mdx
packages/attention/stories/Attention.stories.tsx
tests/eik-react-jsx/index.html
tests/eik-react/index.html
tests/ssr-react-16-cjs/src/server.js
tests/ssr-react-16/server.js
tests/ssr-react-ts-16-cjs/src/server.ts
tests/ssr-react-ts-16/src/server.ts

Before:
After:
Also bumped Fabric css version to v1 so that `drop-shadow-20` class of popover Attention could be applied.

Fix attention docs

---

packages/modal/src/component.tsx

This should ensure that the scroll lock gets removed when the modal closes

fix(modal): cleanup scroll-doctor lock on unmount
